### ISSUE TITLE
[Features] Async Activity Completion is missing in Java

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1456]
# [Async Activity Completion](https://docs.temporal.io/application-development/features?lang=java#async-activity-completion) is missing is Java
 
---
You can provide a code snippet in the comments or a link to the line numbers of the samples-repo. Once added, I'll update the app-dev page with the new code snippet.

**Comment by Spikhalskiy** [comment]
Calling .doNotCompleteOnReturn: https://github.com/temporalio/samples-java/blob/708324ffd1599df4d593b411e9516424be096033/src/main/java/io/temporal/samples/hello/HelloAsyncActivityCompletion.java#L143

Actually completing the activity asynchronously: https://github.com/temporalio/samples-java/blob/708324ffd1599df4d593b411e9516424be096033/src/main/java/io/temporal/samples/hello/HelloAsyncActivityCompletion.java#L155

This example is not that great, because here the same class calls .doNotCompleteOnReturn and completes execution, it's not the best demonstration. But the code snippets are there.
