### ISSUE TITLE
[ Bug report ] Link preview on `#`

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1886]
## Required

**What is the issue?**

Link previews that contains `#` will look up the parent's definition.

**How can we reproduce the issue?**

For example:

[Workflow timeouts](https://docs.temporal.io/workflows#workflow-execution-timeout) page shows: [How to set a Workflow Execution Timeout](https://docs.temporal.io/application-development/features#workflow-retries).

When your cursor hovers over the word it says:

> A Retry Policy can work in cooperation with the timeouts to provide fine controls to optimize the execution experience.

Which is the definition of a Retry Policy and not a **Workflow Execution Timeout**.

> A Workflow Execution Timeout is the maximum time that a Workflow Execution can be executing (have an Open status) including retries and any usage of Continue As New.

**What is the expected behavior?**

To fix this - perhaps write a condition that says, if `#` in link, take first sentence. 

**Screenshots:**

**Browser and version:**

**Device and screen size:**

**Comment by vkarpov15** [comment]
Isn't this just a case of the link being incorrect? The current link is to [the workflow retries anchor](https://docs.temporal.io/application-development/features#workflow-retries), which doesn't include an example of how to set `workflowExecutionTimeout`. Linking to the [Workflow timeouts section](https://docs.temporal.io/application-development/features#workflow-timeouts) does contain an example of setting `workflowExecutionTimeout`, and would also have a better link preview.

![image](https://user-images.githubusercontent.com/1620265/213884121-f67e9a90-3f45-4dc2-9886-eaa9a9f939b2.png)

![image](https://user-images.githubusercontent.com/1620265/213884130-f0b5f828-27d9-413f-8ec2-c2fa4923fc2a.png)

Maybe someone set the link to the workflow retries anchor because of #1740 ?
