### ISSUE TITLE
Document periodic cleanup use case using CRON workflows

### ISSUE THREAD

**Issue by sagikazarmark** [temporalio/documentation#227]
A common use case in all kinds of applications is periodic cleanups of all kinds of resources, typically run in a cron job.

Regular cron schedulers are sadly not fault tolerant though, so for long running cleanup tasks they are not necessarily the best tool.

Temporal also have cron support and can solve the problem in a fault tolerant way.

However, it adds an extra bit of work to the equation: workflows cannot run indefinitely on an infinite number of items. They need to be restarted at some point. For this, a proposed solution is:

> I would start a child workflow from a cron workflow. The child can call continue as new as many times as necessary.  The parent will get child completion only when the last run completes. - @mfateev 

I think it would make sense to include this use case in the documentation, because it comes up more often than we might think.

More details in this thread: https://temporalio.slack.com/archives/CTRCR8RBP/p1610357452380800

**Comment by flossypurse** [comment]
@sw-yx Might be a good opportunity to address this?

**Comment by sw-yx** [comment]
i think this is important to document but would handle this inside the docs rather than in the usecases section of the www site. 

we go partway there with the new section here https://docs.temporal.io/docs/concept-workflows/#faq but we didnt really address the child workflow from cron workflow thing. i think we should address this inside of each sdk's cron page https://docs.temporal.io/docs/go-distributed-cron/

**Comment by flossypurse** [comment]
Finally getting around to this - sorry for the delay.

We have since addressed the high level question of "when" to use Child Workflows here: https://docs.temporal.io/docs/content/what-is-a-child-workflow-execution/#when-to-use-child-workflows
Which does address the use of Continue-As-New

We would love your feedback on that - 

However, @sagikazarmark we are also happy to explore the explicit use case you have mentioned and provide guidance on specific design patterns to address that. If that is the case do you recall some specific "resources" to help with the context for this?

**Comment by flossypurse** [comment]
Just going to drop some links here that explain the concepts and relationships of the things that play into the use case described. 
- https://docs.temporal.io/docs/content/what-is-a-temporal-cron-job/
- https://docs.temporal.io/docs/content/what-is-a-child-workflow-execution/#when-to-use-child-workflows
- https://docs.temporal.io/docs/content/what-is-continue-as-new/

- And this gets into Long-Running design patterns: https://docs.temporal.io/docs/learning-paths/background-checks/project-narrative

So, now going to close this!
