### ISSUE TITLE
[Feature Request] Expand async activity completion docs to include information about heartbeating

### ISSUE THREAD

**Issue by Sushisource** [temporalio/documentation#649]
After chatting with Max and going over some of the concerns related to the interaction between these two concepts I think we need to expand on this in the docs.

We should mention that there are generally two "ways" you can do async activity completion:
* In-process: You return-without-completing from the activity and then in your same process you complete the activity using the task token at some point.
* Out-of-process: You return-without-completing from the activity and hand off the task token somewhere external. Eventually, the activity is async-completed from elsewhere.

In the in process case, it can make sense to use heartbeats (and thus, you must perform them from "outside" of the activity but in the same process to avoid being timed out). You probably would only ever do this because of thread utilization concerns. EX in Java you have 1000s of activities that poll something. You might use async completion here to avoid using a thread-per-activity. In this case it probably makes sense to keep heartbeating.

In the out-of-process case, heartbeating almost certainly does not make sense. Even performing the heartbeat would be somewhat difficult. However, in this case it often makes sense to use an activity/signal combo rather than an async activity. EX: Activity puts something into a queue somewhere, and then the result of the thing-that-might-take-a-long-time is sending a signal back to the workflow.

**Comment by mfateev** [comment]
I think that instead of in-process and out-of-process we should think about failure modes. For example, if an async activity is implemented through some reliable mechanism, for example through a persistent queue, then it doesn't need heartbeating as process failures will not lead to the activity being lost. But if an async activity is sent from one process to another without any persistence involved, then other process heartbeating could be beneficial.

**Comment by sw-yx** [comment]
shall we schedule a meeting to focus on this?

**Comment by flossypurse** [comment]
> In the in process case, it can make sense to use heartbeats (and thus, you must perform them from "outside" of the activity but in the same process to avoid being timed out). 

How does one do that?

**Comment by cretz** [comment]
> How does one do that?

SDK clients have the ability to perform activity heartbeats specifically for async activities.

**Comment by flossypurse** [comment]
>  In-process: You return-without-completing from the activity and then in your same process you complete the activity using the task token at some point.

So, "in-process" = "in Workflow Execution" ?

**Comment by cretz** [comment]
> So, "in-process" = "in Workflow Execution" ?

I think @Sushisource means literally "in OS process". Basically he's differentiating using the task token or ID locally with the client for async activity vs shipping the task token or ID somewhere else for that thing to use a client for async activity.

But @mfateev's point stands about whether the token is reliably handled or not should govern whether heartbeating is used instead of in-process vs out-of-process. This also affects the suggestion of whether to even use async activity (+ heartbeating) vs normal activity completion + signals. I will defer to others on best practices of when to use which.

**Comment by flossypurse** [comment]
> I think @Sushisource means literally "in OS process". Basically he's differentiating using the task token or ID locally with the client for async activity vs shipping the task token or ID somewhere else for that thing to use a client for async activity.

So, for that to happen though, we are also talking about routing Activity Tasks that are doing the Heartbeating to the same OS process that started the initial Activity right?
Because, how can an Activity return but also continue to heart beat from the same OS process?

**Comment by flossypurse** [comment]
I made a call out to Maxim's point here: https://github.com/temporalio/documentation/pull/1210/files#diff-41bea17441cba98f2a36f241745edd0ec7e9303dbdb186a7f25ed2dd2261ef20R19

LMK if how you might want to expand on that?
