### ISSUE TITLE
Create how to configure Go SDK metrics

### ISSUE THREAD

**Issue by aarohib** [temporalio/documentation#851]
https://github.com/temporalio/sdk-go/blob/master/internal/common/metrics/constants.go

**Comment by flossypurse** [comment]
@cretz do you how someone configures Go SDK metrics?
What are the configurable aspects?

Is there an example we can look at?

**Comment by cretz** [comment]
You can set a metrics handler to handle them. https://github.com/temporalio/samples-go/tree/main/metrics shows how to use https://pkg.go.dev/go.temporal.io/sdk/contrib/tally + https://pkg.go.dev/github.com/prometheus/client_golang/prometheus to make them available to Prometheus.

**Comment by flossypurse** [comment]
So, someone has to manually use the handler to emit metrics?
Do you have to also explicitly set which metrics should be emitted?

Trying to understand what we mean when someone says "configure metrics" - sounds like it is actually writing handler logic ?

**Comment by cretz** [comment]
> So, someone has to manually use the handler to emit metrics?

Yes. By default we don't emit them anywhere. There is no one metric system so defaulting to, say, Prometheus is not in the spirit of the SDK. We also have an easy-to-implement https://pkg.go.dev/go.temporal.io/sdk/client#MetricsHandler which they can implement for their favorite library if they don't like the Tally one we provide.

>  Do you have to also explicitly set which metrics should be emitted?

No. This is more of a "handler" than an "emitter". Prometheus obtains and serves them via HTTP so a Prometheus server can collect them. Statsd or OpenTelemetry might push them, etc.

> Trying to understand what we mean when someone says "configure metrics" - sounds like it is actually writing handler logic ?

Probably not. Probably just wiring up to Prometheus or anything else Tally supports. If they do have to write a handler because Tally doesn't support their favorite library, it's fairly trivial. If an unsupported metrics system is wanted across SDKs, we can easily make a standard implementation for it.

**Comment by flossypurse** [comment]
This is done.
If there are new or other specific things - we can track those separately.
