### ISSUE TITLE
"Glossary" not discoverable

### ISSUE THREAD

**Issue by sw-yx** [temporalio/documentation#91]
hi gang!

I'm not sure how i found it but I randomly found https://docs.temporal.io/docs/learn-glossary/ yesterday. I find it very helpful for understanding Temporal. I was looking for it again today and couldnt find it. I realized this is because it is not in the left nav where i would expect it.

<img src="https://user-images.githubusercontent.com/6764957/90583394-98d30680-e202-11ea-833c-2deca92ac596.png" height=300 />

I'm not sure where you envision it - i was about to open a PR to add it to the sidebar (https://github.com/temporalio/documentation/blob/0fecab75c52b36cbe67920e378e5662efa88d3c0/sidebars.js#L8-L17) but then the "learn_" prefix made me stop and think if you are setting up a separate learn section or something? So i figured i better file an issue.

Shawn

**Comment by cullywakelin** [comment]
Ya, I had plans to disperse that content throughout the concepts - 
But, that plan seems like a long way off now :)
And since this is actual a good source of concept definitions and is referenced by other pages, I think you are correct in wanting this to be available in the menu.

PR: https://github.com/temporalio/documentation/pull/124
